/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: letter-movements.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "letter-movements.pb-c.h"
void   position__init
                     (Position         *message)
{
  static const Position init_value = POSITION__INIT;
  *message = init_value;
}
size_t position__get_packed_size
                     (const Position *message)
{
  assert(message->base.descriptor == &position__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t position__pack
                     (const Position *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &position__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t position__pack_to_buffer
                     (const Position *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &position__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Position *
       position__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Position *)
     protobuf_c_message_unpack (&position__descriptor,
                                allocator, len, data);
}
void   position__free_unpacked
                     (Position *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &position__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   connect_request__init
                     (ConnectRequest         *message)
{
  static const ConnectRequest init_value = CONNECT_REQUEST__INIT;
  *message = init_value;
}
size_t connect_request__get_packed_size
                     (const ConnectRequest *message)
{
  assert(message->base.descriptor == &connect_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t connect_request__pack
                     (const ConnectRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &connect_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t connect_request__pack_to_buffer
                     (const ConnectRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &connect_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ConnectRequest *
       connect_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ConnectRequest *)
     protobuf_c_message_unpack (&connect_request__descriptor,
                                allocator, len, data);
}
void   connect_request__free_unpacked
                     (ConnectRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &connect_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   movement_request__init
                     (MovementRequest         *message)
{
  static const MovementRequest init_value = MOVEMENT_REQUEST__INIT;
  *message = init_value;
}
size_t movement_request__get_packed_size
                     (const MovementRequest *message)
{
  assert(message->base.descriptor == &movement_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t movement_request__pack
                     (const MovementRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &movement_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t movement_request__pack_to_buffer
                     (const MovementRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &movement_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MovementRequest *
       movement_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MovementRequest *)
     protobuf_c_message_unpack (&movement_request__descriptor,
                                allocator, len, data);
}
void   movement_request__free_unpacked
                     (MovementRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &movement_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   server_response__init
                     (ServerResponse         *message)
{
  static const ServerResponse init_value = SERVER_RESPONSE__INIT;
  *message = init_value;
}
size_t server_response__get_packed_size
                     (const ServerResponse *message)
{
  assert(message->base.descriptor == &server_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t server_response__pack
                     (const ServerResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &server_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t server_response__pack_to_buffer
                     (const ServerResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &server_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ServerResponse *
       server_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ServerResponse *)
     protobuf_c_message_unpack (&server_response__descriptor,
                                allocator, len, data);
}
void   server_response__free_unpacked
                     (ServerResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &server_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor position__field_descriptors[2] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(Position, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(Position, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned position__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange position__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor position__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Position",
  "Position",
  "Position",
  "",
  sizeof(Position),
  2,
  position__field_descriptors,
  position__field_indices_by_name,
  1,  position__number_ranges,
  (ProtobufCMessageInit) position__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor connect_request__field_descriptors[1] =
{
  {
    "letter",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ConnectRequest, letter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned connect_request__field_indices_by_name[] = {
  0,   /* field[0] = letter */
};
static const ProtobufCIntRange connect_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor connect_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "connect_request",
  "ConnectRequest",
  "ConnectRequest",
  "",
  sizeof(ConnectRequest),
  1,
  connect_request__field_descriptors,
  connect_request__field_indices_by_name,
  1,  connect_request__number_ranges,
  (ProtobufCMessageInit) connect_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor movement_request__field_descriptors[2] =
{
  {
    "letter",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MovementRequest, letter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MovementRequest, direction),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned movement_request__field_indices_by_name[] = {
  1,   /* field[1] = direction */
  0,   /* field[0] = letter */
};
static const ProtobufCIntRange movement_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor movement_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "movement_request",
  "MovementRequest",
  "MovementRequest",
  "",
  sizeof(MovementRequest),
  2,
  movement_request__field_descriptors,
  movement_request__field_indices_by_name,
  1,  movement_request__number_ranges,
  (ProtobufCMessageInit) movement_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue server_response__response_type__enum_values_by_number[2] =
{
  { "CONNECT", "SERVER_RESPONSE__RESPONSE_TYPE__CONNECT", 1 },
  { "MOVEMENT", "SERVER_RESPONSE__RESPONSE_TYPE__MOVEMENT", 2 },
};
static const ProtobufCIntRange server_response__response_type__value_ranges[] = {
{1, 0},{0, 2}
};
static const ProtobufCEnumValueIndex server_response__response_type__enum_values_by_name[2] =
{
  { "CONNECT", 0 },
  { "MOVEMENT", 1 },
};
const ProtobufCEnumDescriptor server_response__response_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "server_response.ResponseType",
  "ResponseType",
  "ServerResponse__ResponseType",
  "",
  2,
  server_response__response_type__enum_values_by_number,
  2,
  server_response__response_type__enum_values_by_name,
  1,
  server_response__response_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor server_response__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ServerResponse, type),
    &server_response__response_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "success",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ServerResponse, success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned server_response__field_indices_by_name[] = {
  1,   /* field[1] = success */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange server_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor server_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "server_response",
  "ServerResponse",
  "ServerResponse",
  "",
  sizeof(ServerResponse),
  2,
  server_response__field_descriptors,
  server_response__field_indices_by_name,
  1,  server_response__number_ranges,
  (ProtobufCMessageInit) server_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
