/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: letter-movements.proto */

#ifndef PROTOBUF_C_letter_2dmovements_2eproto__INCLUDED
#define PROTOBUF_C_letter_2dmovements_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct PbPosition PbPosition;
typedef struct ConnectRequest ConnectRequest;
typedef struct MovementRequest MovementRequest;
typedef struct ServerResponse ServerResponse;


/* --- enums --- */

typedef enum _ServerResponse__ResponseType {
  SERVER_RESPONSE__RESPONSE_TYPE__CONNECT = 1,
  SERVER_RESPONSE__RESPONSE_TYPE__MOVEMENT = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SERVER_RESPONSE__RESPONSE_TYPE)
} ServerResponse__ResponseType;

/* --- messages --- */

struct  PbPosition
{
  ProtobufCMessage base;
  int32_t x;
  int32_t y;
};
#define POSITION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&position__descriptor) \
   , 0, 0 }


/*
 * Client connection request - sent when client wants to connect with a letter
 */
struct  ConnectRequest
{
  ProtobufCMessage base;
  /*
   * The character/letter the client wants to use
   */
  ProtobufCBinaryData letter;
};
#define CONNECT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connect_request__descriptor) \
    , {0,NULL} }


/*
 * Client movement request - sent when client moves their letter
 */
struct  MovementRequest
{
  ProtobufCMessage base;
  /*
   * The character being moved
   */
  ProtobufCBinaryData letter;
  /*
   * Position: X/Y coordinates of the letter
   */
  PbPosition *position;
};
#define MOVEMENT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&movement_request__descriptor) \
   , {0,NULL}, NULL }


/*
 * Unified server response - used for both connection and movement responses
 */
struct  ServerResponse
{
  ProtobufCMessage base;
  /*
   * Type of response
   */
  ServerResponse__ResponseType type;
  /*
   * true = OK/accepted, false = NOT OK/WALL
   */
  protobuf_c_boolean success;
};
#define SERVER_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&server_response__descriptor) \
    , SERVER_RESPONSE__RESPONSE_TYPE__CONNECT, 0 }


/* Position methods */
void   position__init
  (PbPosition         *message);
size_t position__get_packed_size
  (const PbPosition   *message);
size_t position__pack
  (const PbPosition   *message,
       uint8_t          *out);
size_t position__pack_to_buffer
  (const PbPosition   *message,
       ProtobufCBuffer  *buffer);
PbPosition *
  position__unpack
    (ProtobufCAllocator  *allocator,
     size_t               len,
     const uint8_t       *data);
  void   position__free_unpacked
    (PbPosition *message,
       ProtobufCAllocator *allocator);
/* ConnectRequest methods */
void   connect_request__init
                     (ConnectRequest         *message);
size_t connect_request__get_packed_size
                     (const ConnectRequest   *message);
size_t connect_request__pack
                     (const ConnectRequest   *message,
                      uint8_t             *out);
size_t connect_request__pack_to_buffer
                     (const ConnectRequest   *message,
                      ProtobufCBuffer     *buffer);
ConnectRequest *
       connect_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connect_request__free_unpacked
                     (ConnectRequest *message,
                      ProtobufCAllocator *allocator);
/* MovementRequest methods */
void   movement_request__init
                     (MovementRequest         *message);
size_t movement_request__get_packed_size
                     (const MovementRequest   *message);
size_t movement_request__pack
                     (const MovementRequest   *message,
                      uint8_t             *out);
size_t movement_request__pack_to_buffer
                     (const MovementRequest   *message,
                      ProtobufCBuffer     *buffer);
MovementRequest *
       movement_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   movement_request__free_unpacked
                     (MovementRequest *message,
                      ProtobufCAllocator *allocator);
/* ServerResponse methods */
void   server_response__init
                     (ServerResponse         *message);
size_t server_response__get_packed_size
                     (const ServerResponse   *message);
size_t server_response__pack
                     (const ServerResponse   *message,
                      uint8_t             *out);
size_t server_response__pack_to_buffer
                     (const ServerResponse   *message,
                      ProtobufCBuffer     *buffer);
ServerResponse *
       server_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   server_response__free_unpacked
                     (ServerResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Position_Closure)
                 (const PbPosition *message,
                  void *closure_data);
typedef void (*ConnectRequest_Closure)
                 (const ConnectRequest *message,
                  void *closure_data);
typedef void (*MovementRequest_Closure)
                 (const MovementRequest *message,
                  void *closure_data);
typedef void (*ServerResponse_Closure)
                 (const ServerResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor position__descriptor;
extern const ProtobufCMessageDescriptor connect_request__descriptor;
extern const ProtobufCMessageDescriptor movement_request__descriptor;
extern const ProtobufCMessageDescriptor server_response__descriptor;
extern const ProtobufCEnumDescriptor    server_response__response_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_letter_2dmovements_2eproto__INCLUDED */
